name: Build and Deploy Resume
on:
  push:
    paths:
      - '**.tex'
      - '**.sty'
      - 'sections/**.tex'
      - '.github/workflows/compile_resume.yml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: List directory structure (for debugging)
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          echo "Sections directory:"
          ls -la sections/ || echo "Sections directory not found"
      
      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          # Using appropriate fonts that are available in the container
          # The texlive-full image already has most packages we need
          latexmk_shell_escape: true  # Enable shell escape for tikz
          pre_compile: |
            # Install the fontawesome package if needed
            tlmgr update --self
            tlmgr install fontawesome || echo "fontawesome already installed"
            tlmgr install sourcesanspro || echo "sourcesanspro already installed"
            tlmgr install tcolorbox || echo "tcolorbox already installed"
      
      - name: Upload compiled PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: resume.pdf
      
      # Setup GitHub Pages deployment
      - name: Prepare for GitHub Pages
        run: |
          mkdir -p deploy
          if [ -f "resume.pdf" ]; then
            cp resume.pdf deploy/
            echo "Resume PDF found and copied to deploy directory"
          else
            echo "Resume PDF not found! Listing current directory:"
            ls -la
            # Create a placeholder file to prevent deployment failure
            echo "Resume compilation failed. Please check the workflow logs." > deploy/compilation-failed.txt
          fi
          
          # Create a simple index.html page
          cat > deploy/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>Berkin Deniz Kahya's Resume</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
              }
              .container {
                background-color: #f9f9f9;
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              h1 {
                color: #3A5A80;
                border-bottom: 2px solid #3A5A80;
                padding-bottom: 10px;
              }
              .download-button {
                display: inline-block;
                background-color: #3A5A80;
                color: white;
                padding: 12px 24px;
                text-decoration: none;
                border-radius: 4px;
                font-weight: bold;
                margin-top: 20px;
                transition: background-color 0.3s;
              }
              .download-button:hover {
                background-color: #2A4A70;
              }
              .update-info {
                font-style: italic;
                color: #666;
                margin-top: 30px;
                font-size: 0.9em;
              }
              .links {
                margin-top: 30px;
              }
              .links a {
                color: #3A5A80;
                text-decoration: none;
                margin-right: 15px;
              }
              .links a:hover {
                text-decoration: underline;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Berkin Deniz Kahya</h1>
              <p> Resume page testing... </p>
              
              <a class="download-button" href="resume.pdf"> download my resume (PDF)</a>
              
              <div class="links">
                <a href="https://github.com/denizberkin" target="_blank">GitHub</a>
                <a href="https://www.linkedin.com/in/denizberkin" target="_blank">LinkedIn</a>
              </div>
              
              <p class="update-info">Last updated: $(date +'%B %d, %Y')</p>
            </div>
          </body>
          </html>
          EOF
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages